# Original flags from reference/ultralib/makefiles/ido.mk.
$(BUILD_DIR)/$(SRC_DIR)/libultra/aisetfreq.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/aisetfreq.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/aisetfreq.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapalloc.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapalloc.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapalloc.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/createmesgqueue.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/createmesgqueue.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/createmesgqueue.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/createthread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/createthread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/createthread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/startthread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/startthread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/startthread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/recvmesg.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/recvmesg.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/recvmesg.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/virtualtophysical.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/virtualtophysical.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/virtualtophysical.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/aigetlen.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/aigetlen.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/aigetlen.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sendmesg.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sendmesg.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sendmesg.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/pidma.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/pidma.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/pidma.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/syncprintf.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/syncprintf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/syncprintf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seteventmesg.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/seteventmesg.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seteventmesg.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/contsetch.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/contsetch.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/contsetch.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/coss.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/coss.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/coss.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/ortho.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/ortho.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/ortho.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/lookat.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/lookat.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/lookat.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetmode.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetmode.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetmode.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapbuf.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapbuf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapbuf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/setthreadpri.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/setthreadpri.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/setthreadpri.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/stopthread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/stopthread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/stopthread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetevent.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetevent.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetevent.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetspecial.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetspecial.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetspecial.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/viblack.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/viblack.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/viblack.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetyscale.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetyscale.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetyscale.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetxscale.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetxscale.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/visetxscale.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetstat.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetstat.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetstat.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetsound.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetsound.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetsound.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpgetstate.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpgetstate.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpgetstate.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapinit.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapinit.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/heapinit.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/bnkf.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/bnkf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/bnkf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetbank.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetbank.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetbank.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetseq.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetseq.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetseq.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetvol.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetvol.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetvol.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpplay.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpplay.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpplay.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpallocate.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpallocate.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpallocate.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpriority.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpriority.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpriority.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetfxmix.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetfxmix.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetfxmix.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpitch.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpitch.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpitch.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetvol.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetvol.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetvol.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpan.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpan.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpsetpan.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpplay.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpplay.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpplay.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpstop.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpstop.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpstop.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpdeallocate.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpdeallocate.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpdeallocate.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpstop.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpstop.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sndpstop.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetchlvol.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetchlvol.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/seqpsetchlvol.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/translate.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/translate.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/translate.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/scale.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/scale.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/scale.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatf.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatl.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatl.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/mtxcatl.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/syndelete.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/syndelete.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/syndelete.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyielded.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyielded.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyielded.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrframebuf.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrframebuf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrframebuf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetnextframebuf.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetnextframebuf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetnextframebuf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/dpsetnextbuf.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/dpsetnextbuf.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/dpsetnextbuf.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyield.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyield.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sptaskyield.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/ai.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/ai.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/ai.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocfx.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocfx.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocfx.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/mainbus.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/mainbus.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/mainbus.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/auxbus.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/auxbus.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/auxbus.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/save.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/save.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/save.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/jammesg.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/jammesg.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/jammesg.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetcmdq.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetcmdq.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/pigetcmdq.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawdma.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawdma.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawdma.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/crc.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/crc.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/crc.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/gettime.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/gettime.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/gettime.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/settimer.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/settimer.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/settimer.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/normalize.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/normalize.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/normalize.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawwrite.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawwrite.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sirawwrite.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/getthreadpri.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/getthreadpri.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/getthreadpri.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrcontext.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrcontext.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/vigetcurrcontext.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapcontext.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapcontext.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/viswapcontext.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawdma.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawdma.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/pirawdma.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/epirawdma.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/epirawdma.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/epirawdma.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/event.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/event.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/event.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synaddplayer.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synaddplayer.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synaddplayer.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstopvoice.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstopvoice.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstopvoice.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synfreevoice.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synfreevoice.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synfreevoice.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetvol.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetvol.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetvol.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpitch.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpitch.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpitch.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocvoice.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocvoice.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synallocvoice.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoiceparam.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoiceparam.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoiceparam.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpan.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpan.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpan.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetfxmix.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetfxmix.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetfxmix.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoice.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoice.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synstartvoice.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/spgetstat.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/spgetstat.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/spgetstat.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetstat.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetstat.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetstat.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetpc.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetpc.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/spsetpc.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sprawdma.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sprawdma.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sprawdma.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/sp.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/sp.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/sp.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/dp.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/dp.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/dp.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/filter.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/filter.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/filter.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/copy.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/copy.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/copy.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/si.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/si.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/si.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/resetglobalintmask.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/resetglobalintmask.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/resetglobalintmask.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/setglobalintmask.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/setglobalintmask.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/setglobalintmask.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/yieldthread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/yieldthread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/yieldthread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpriority.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpriority.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/synsetpriority.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/ll.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/ll.c.o: MIPSISET := -mips3 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/ll.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/initialize.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/initialize.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/initialize.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/thread.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/thread.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/thread.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/load.c.o: OPT_FLAGS := -O3
$(BUILD_DIR)/$(SRC_DIR)/libultra/load.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/load.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/timerintr.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/timerintr.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/timerintr.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
$(BUILD_DIR)/$(SRC_DIR)/libultra/leointerrupt.c.o: OPT_FLAGS := -O1
$(BUILD_DIR)/$(SRC_DIR)/libultra/leointerrupt.c.o: MIPSISET := -mips2 -32
$(BUILD_DIR)/$(SRC_DIR)/libultra/leointerrupt.c.o: CFLAGS := -I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra $(CFLAGS)
