"""Regenerate GNU Make overrides from the reference libultra source manifest."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
sources = json.loads((root / "src.us/libultra/sources.json").read_text())
includes = "-I $(SRC_DIR)/libultra/include -I $(SRC_DIR)/libultra/include/PR -I $(SRC_DIR)/libultra"
lines = ["# Generated by tools/generate_libultra_flags.py from sources.json.",
         "# Original flags: reference/ultralib/makefiles/ido.mk."]
for name, config in sources.items():
    target = f"$(BUILD_DIR)/$(SRC_DIR)/libultra/{name}.c.o"
    cflags = "$(CFLAGS)"
    check = "$(CC_CHECK)"
    if config.get("signed_char") is False:
        cflags = "$(filter-out -signed,$(CFLAGS))"
        check = "$(subst -fsigned-char,-funsigned-char,$(CC_CHECK))"
    lines.extend([
        f"{target}: OPT_FLAGS := {config['optimization']}",
        f"{target}: MIPSISET := {config['isa']} -32",
        f"{target}: CFLAGS := {includes} {cflags}",
        f"{target}: CC_CHECK := $(subst $(INCLUDE_CFLAGS),{includes} $(INCLUDE_CFLAGS),{check})",
    ])
(root / "src.us/libultra/compiler_flags.mk").write_text(
    "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
